[package]
name = "mygit"
version = "0.1.0"
authors = ["musou1500 <musou1500@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
chrono = "0.4.38"
dirs = "5.0.1"
flate2 = "1.0.34"
rust-crypto = "0.2.36"
rust-ini = "0.21.1"
sha1 = "0.10.6"
